#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
================================================================================
Excel Sanity Checker - A.5.7.1 Threat Intelligence Sources Assessment Workbook
================================================================================

ISO/IEC 27001:2022 Control A.5.7: Threat Intelligence
Assessment Domain: 1 of 5 (Threat Intelligence Sources Portfolio Management)
Script Type: Domain-Specific QA Utility
Version: 2.0

SPECIALIZED diagnostic for Threat Intelligence Sources Assessment workbooks
(15 sheets) generated by generate_a57_1_sources.py.

--------------------------------------------------------------------------------
PURPOSE
--------------------------------------------------------------------------------

Domain-specific validation tailored to the unique structure and requirements
of A.5.7.1 Threat Intelligence Sources Assessment workbooks.

This checker validates threat intelligence source portfolio management
assessment integrity, including CVSS support tracking (VTL integration),
source quality metrics, vendor management, and audit-critical validation sheets.

--------------------------------------------------------------------------------
CHECKS PERFORMED
--------------------------------------------------------------------------------

**Structural Validation (15 Sheets v2.0):**
- Instructions, Source_Inventory, Source_Evaluation, Coverage_Matrix
- Cost_Analysis, Compliance_Check, Action_Items, Metadata
- Integration_Points, Update_Frequency, Source_Contacts, Vendor_SLAs
- API_Integration, Source_Performance_Validation (AUDIT CRITICAL)
- Business_Continuity_Plan (AUDIT CRITICAL)

**Formula Integrity:**
- CVSS accuracy calculations (Sheet 3: Source_Evaluation)
- Cost-per-indicator formulas (Sheet 5: Cost_Analysis)
- Compliance scoring (Sheet 6: Compliance_Check)
- Coverage gap analysis (Sheet 4: Coverage_Matrix)
- SLA compliance percentages (Sheets 10, 12)
- IFERROR wrappers on VLOOKUP formulas

**Data Validation Rules:**
- CVSS support: "4.0 Full", "4.0 Basic", "3.1 Full", "3.1 Basic", "2.0", "None"
- Source types: "Commercial", "Open Source", "Government/CERT", "ISAC/ISAO", "Internal"
- Quality ratings: "Excellent", "Good", "Acceptable", "Poor"
- SLA status: "Met", "Degraded", "Violated", "N/A"

**VTL Integration (CRITICAL):**
- CVSS_Support column present (Sheet 2: Source_Inventory, Column K)
- CVSS accuracy tracking columns (Sheet 3: Source_Evaluation)
- CVSS accuracy conditional formatting (GREEN >90%, YELLOW 85-90%, RED <85%)

**Audit-Critical Sheets:**
- Sheet 14 (Source_Performance_Validation): Quarterly data present
- Sheet 15 (Business_Continuity_Plan): Contingency procedures documented

--------------------------------------------------------------------------------
WHEN TO USE
--------------------------------------------------------------------------------

- After generating A.5.7.1 Sources Assessment workbook
- Before stakeholder distribution or audit submission
- After manual edits to validate formula integrity
- Quarterly before performance validation updates (Sheet 14)
- Before dashboard generation (A.5.7.4 requires clean inputs)
- When Excel shows repair warnings

--------------------------------------------------------------------------------
USAGE
--------------------------------------------------------------------------------

    python3 excel_sanity_check_a57_1.py ISMS_A_5_7_1_Sources_Assessment_20250115.xlsx

Exit Codes:
    0 = All checks passed (workbook ready for distribution)
    1 = Warnings found (minor issues, workbook functional)
    2 = Errors found (significant problems requiring attention)
    3 = Critical failures (workbook unusable, regeneration recommended)

--------------------------------------------------------------------------------
DIFFERENCES FROM GENERAL CHECKER
--------------------------------------------------------------------------------

This SPECIALIZED A.5.7.1 checker validates domain-specific requirements that
generic Excel validators cannot verify:
- Exact 15-sheet structure per A.5.7.1 specification
- CVSS accuracy tracking formulas (VTL workflow critical)
- Source quality scoring specific to threat intelligence
- Vendor management sheet completeness (Sheets 9-13)
- Quarterly validation requirements (Sheet 14 - audit evidence)
- Business continuity plan documentation (Sheet 15 - audit evidence)
- A.5.7.1-specific data validation dropdowns and conditional formatting

Cannot be replaced by generic tools - requires domain knowledge.

Control Reference: ISO/IEC 27001:2022 Annex A Control A.5.7
Related Script:    generate_a57_1_sources.py (workbook generator)
Framework Version: 2.0 (15 sheets, CVSS tracking, VTL integration)
================================================================================
"""

import sys
import re
from openpyxl import load_workbook
from openpyxl.utils import get_column_letter


# Expected workbook structure v2.0 (15 sheets)
EXPECTED_SHEETS = [
    "Instructions",
    "Source_Inventory",
    "Source_Evaluation",
    "Coverage_Matrix",
    "Cost_Analysis",
    "Compliance_Check",
    "Action_Items",
    "Metadata",
    "Integration_Points",              # NEW v2.0
    "Update_Frequency",                # NEW v2.0
    "Source_Contacts",                 # NEW v2.0
    "Vendor_SLAs",                     # NEW v2.0
    "API_Integration",                 # NEW v2.0
    "Source_Performance_Validation",   # NEW v2.0 - AUDIT CRITICAL
    "Business_Continuity_Plan",        # NEW v2.0 - AUDIT CRITICAL
]


def check_workbook_health(filename):
    """Comprehensive validation for A.5.7.1 Sources workbook v2.0."""
    
    print("=" * 80)
    print(f"SANITY CHECK: {filename}")
    print("ISMS-IMP-A.5.7.1 v2.0 - Threat Intelligence Sources Assessment (15 Sheets)")
    print("=" * 80)
    
    issues_found = []
    warnings_found = []
    
    try:
        wb = load_workbook(filename, data_only=False)
        print(f"\n✓ Workbook loaded successfully")
        print(f"  Sheets found: {len(wb.sheetnames)}")
    except Exception as e:
        print(f"\n✗ CRITICAL: Cannot load workbook: {e}")
        return
    
    # ========================================================================
    # CHECK 1: SHEET STRUCTURE (v2.0 - 15 sheets)
    # ========================================================================
    print("\n" + "=" * 80)
    print("CHECK 1: SHEET STRUCTURE (v2.0)")
    print("=" * 80)
    
    if len(wb.sheetnames) != 15:
        issues_found.append(f"  ✗ Expected 15 sheets (v2.0), found {len(wb.sheetnames)}")
    else:
        print(f"  ✓ Sheet count: 15 (v2.0)")
    
    for sheet_name in EXPECTED_SHEETS:
        if sheet_name in wb.sheetnames:
            if sheet_name in ["Source_Performance_Validation", "Business_Continuity_Plan"]:
                print(f"  ✓ Found: {sheet_name} (AUDIT CRITICAL)")
            else:
                print(f"  ✓ Found: {sheet_name}")
        else:
            issues_found.append(f"  ✗ Missing sheet: {sheet_name}")
    
    # ========================================================================
    # CHECK 2: SOURCE_INVENTORY VALIDATION (v2.0 - CVSS_Support column)
    # ========================================================================
    print("\n" + "=" * 80)
    print("CHECK 2: SOURCE_INVENTORY VALIDATION (v2.0)")
    print("=" * 80)
    
    if "Source_Inventory" in wb.sheetnames:
        ws = wb["Source_Inventory"]
        
        # Check for CVSS_Support column header (should be column K)
        cvss_header = ws["K4"].value
        if cvss_header and "CVSS" in str(cvss_header).upper():
            print(f"  ✓ CVSS_Support column found (K4): {cvss_header}")
        else:
            issues_found.append(f"  ✗ CVSS_Support column missing or incorrect (K4)")
        
        # Check total columns (expanded from 15 to 16)
        if ws["P4"].value:  # Column P is the last column
            print(f"  ✓ Source_Inventory: 16 columns present (expanded for CVSS)")
        else:
            warnings_found.append(f"  ⚠ Source_Inventory: Column count may be incomplete")
        
        # Check for data validation on CVSS_Support column
        cvss_validation_found = False
        for dv in ws.data_validations.dataValidation:
            if any("K" in str(cell) for cell in dv.cells):
                cvss_validation_found = True
                break
        
        if cvss_validation_found:
            print(f"  ✓ CVSS_Support validation dropdown present")
        else:
            warnings_found.append(f"  ⚠ CVSS_Support validation not detected")
        
        # Check for conditional formatting on CVSS_Support column
        cvss_cf_found = len(ws.conditional_formatting) > 0
        if cvss_cf_found:
            print(f"  ✓ Conditional formatting present (CVSS color scale)")
        else:
            warnings_found.append(f"  ⚠ Conditional formatting not detected")
    
    # ========================================================================
    # CHECK 3: SOURCE_EVALUATION (v2.0 - CVSS accuracy columns)
    # ========================================================================
    print("\n" + "=" * 80)
    print("CHECK 3: SOURCE_EVALUATION (v2.0 - CVSS ACCURACY)")
    print("=" * 80)
    
    if "Source_Evaluation" in wb.sheetnames:
        ws = wb["Source_Evaluation"]
        
        # Check for new CVSS accuracy columns (R, S, T)
        cvss_accuracy_header = ws["R4"].value
        cvss_sample_header = ws["S4"].value
        cvss_date_header = ws["T4"].value
        
        cvss_columns_ok = True
        if cvss_accuracy_header and "CVSS" in str(cvss_accuracy_header).upper() and "ACCURACY" in str(cvss_accuracy_header).upper():
            print(f"  ✓ CVSS_Accuracy_Rate column (R4): {cvss_accuracy_header}")
        else:
            issues_found.append(f"  ✗ CVSS_Accuracy_Rate column missing (R4)")
            cvss_columns_ok = False
        
        if cvss_sample_header and "SAMPLE" in str(cvss_sample_header).upper():
            print(f"  ✓ CVSS_Sample_Size column (S4): {cvss_sample_header}")
        else:
            issues_found.append(f"  ✗ CVSS_Sample_Size column missing (S4)")
            cvss_columns_ok = False
        
        if cvss_date_header and "VALIDATION" in str(cvss_date_header).upper() and "DATE" in str(cvss_date_header).upper():
            print(f"  ✓ CVSS_Validation_Date column (T4): {cvss_date_header}")
        else:
            issues_found.append(f"  ✗ CVSS_Validation_Date column missing (T4)")
            cvss_columns_ok = False
        
        if cvss_columns_ok:
            print(f"  ✓ All 3 CVSS accuracy columns present")
        
        # Check for conditional formatting on CVSS_Accuracy_Rate column
        cvss_cf_found = len(ws.conditional_formatting) > 0
        if cvss_cf_found:
            print(f"  ✓ Conditional formatting present (CVSS accuracy thresholds)")
        else:
            warnings_found.append(f"  ⚠ Conditional formatting not detected")
    
    # ========================================================================
    # CHECK 4: COVERAGE_MATRIX VALIDATION (unchanged from v1.0)
    # ========================================================================
    print("\n" + "=" * 80)
    print("CHECK 4: COVERAGE_MATRIX VALIDATION")
    print("=" * 80)
    
    if "Coverage_Matrix" in wb.sheetnames:
        ws = wb["Coverage_Matrix"]
        
        # Check for 3 sub-tables: Geographic, Sector, Threat Type
        sections_found = 0
        for row in range(1, 100):
            cell_val = ws[f"A{row}"].value
            if cell_val and isinstance(cell_val, str):
                if "GEOGRAPHIC" in cell_val.upper():
                    sections_found += 1
                    print(f"  ✓ Coverage_Matrix: Geographic section found (row {row})")
                elif "SECTOR" in cell_val.upper() or "INDUSTRY" in cell_val.upper():
                    sections_found += 1
                    print(f"  ✓ Coverage_Matrix: Sector section found (row {row})")
                elif "THREAT" in cell_val.upper():
                    sections_found += 1
                    print(f"  ✓ Coverage_Matrix: Threat Type section found (row {row})")
        
        if sections_found < 3:
            warnings_found.append(f"  ⚠ Coverage_Matrix: Only {sections_found}/3 sections found")
    
    # ========================================================================
    # CHECK 5: VENDOR MANAGEMENT SHEETS (NEW v2.0 - Sheets 9-13)
    # ========================================================================
    print("\n" + "=" * 80)
    print("CHECK 5: VENDOR MANAGEMENT SHEETS (NEW v2.0)")
    print("=" * 80)
    
    vendor_sheets = [
        ("Integration_Points", "Integration_Type"),
        ("Update_Frequency", "Contractual_Frequency"),
        ("Source_Contacts", "Contact_Type"),
        ("Vendor_SLAs", "SLA_Metric"),
        ("API_Integration", "API_Version"),
    ]
    
    for sheet_name, expected_column in vendor_sheets:
        if sheet_name in wb.sheetnames:
            ws = wb[sheet_name]
            # Check for expected column header in row 4
            header_found = False
            for col in range(1, 30):
                col_letter = get_column_letter(col)
                header_val = ws[f"{col_letter}4"].value
                if header_val and expected_column.upper() in str(header_val).upper():
                    header_found = True
                    break
            
            if header_found:
                print(f"  ✓ {sheet_name}: '{expected_column}' column found")
            else:
                warnings_found.append(f"  ⚠ {sheet_name}: '{expected_column}' column not found")
        else:
            issues_found.append(f"  ✗ {sheet_name}: Sheet missing")
    
    # ========================================================================
    # CHECK 6: SOURCE_PERFORMANCE_VALIDATION (AUDIT CRITICAL - Sheet 14)
    # ========================================================================
    print("\n" + "=" * 80)
    print("CHECK 6: SOURCE_PERFORMANCE_VALIDATION (AUDIT CRITICAL)")
    print("=" * 80)
    
    if "Source_Performance_Validation" in wb.sheetnames:
        ws = wb["Source_Performance_Validation"]
        
        # Check for critical columns
        critical_columns = {
            "IOC_Sample_Size": None,
            "CVE_Sample_Size": None,
            "IOC_Accuracy": None,
            "CVE_Accuracy": None,
            "CVSS_Accuracy_Rate": None,
            "Overall_Accuracy_Rate": None,
            "Validation_Pass": None,
        }
        
        for col in range(1, 40):
            col_letter = get_column_letter(col)
            header_val = ws[f"{col_letter}4"].value
            if header_val:
                for key in critical_columns.keys():
                    if key.upper() in str(header_val).upper():
                        critical_columns[key] = col_letter
        
        all_columns_found = True
        for column, col_letter in critical_columns.items():
            if col_letter:
                print(f"  ✓ Sheet 14: '{column}' column found ({col_letter})")
            else:
                issues_found.append(f"  ✗ Sheet 14: '{column}' column MISSING")
                all_columns_found = False
        
        # Check for formulas in accuracy columns (should have formulas)
        if all_columns_found:
            formula_checks = [
                ("IOC_Accuracy", critical_columns["IOC_Accuracy"]),
                ("CVE_Accuracy", critical_columns["CVE_Accuracy"]),
                ("CVSS_Accuracy_Rate", critical_columns["CVSS_Accuracy_Rate"]),
                ("Overall_Accuracy_Rate", critical_columns["Overall_Accuracy_Rate"]),
                ("Validation_Pass", critical_columns["Validation_Pass"]),
            ]
            
            for name, col_letter in formula_checks:
                if col_letter:
                    cell_val = ws[f"{col_letter}5"].value
                    if cell_val and isinstance(cell_val, str) and cell_val.startswith("="):
                        print(f"  ✓ Sheet 14: {name} formula present ({col_letter}5)")
                    else:
                        issues_found.append(f"  ✗ Sheet 14: {name} formula MISSING ({col_letter}5)")
        
        # Check for conditional formatting (accuracy thresholds)
        if len(ws.conditional_formatting) > 0:
            print(f"  ✓ Sheet 14: Conditional formatting present ({len(ws.conditional_formatting)} rules)")
        else:
            warnings_found.append(f"  ⚠ Sheet 14: No conditional formatting detected")
        
    else:
        issues_found.append(f"  ✗ Sheet 14 (Source_Performance_Validation) MISSING - AUDIT CRITICAL")
    
    # ========================================================================
    # CHECK 7: BUSINESS_CONTINUITY_PLAN (AUDIT CRITICAL - Sheet 15)
    # ========================================================================
    print("\n" + "=" * 80)
    print("CHECK 7: BUSINESS_CONTINUITY_PLAN (AUDIT CRITICAL)")
    print("=" * 80)
    
    if "Business_Continuity_Plan" in wb.sheetnames:
        ws = wb["Business_Continuity_Plan"]
        
        # Check for critical columns
        critical_columns_bc = {
            "Role_Category": None,
            "Primary_Person_Name": None,
            "Backup_Person_Name": None,
            "Primary_Training_Complete": None,
            "Backup_Training_Complete": None,
            "Last_Continuity_Test_Date": None,
            "Last_Test_Result": None,
            "Compliance_Status": None,
        }
        
        for col in range(1, 40):
            col_letter = get_column_letter(col)
            header_val = ws[f"{col_letter}4"].value
            if header_val:
                for key in critical_columns_bc.keys():
                    if key.upper() in str(header_val).upper():
                        critical_columns_bc[key] = col_letter
        
        all_bc_columns_found = True
        for column, col_letter in critical_columns_bc.items():
            if col_letter:
                print(f"  ✓ Sheet 15: '{column}' column found ({col_letter})")
            else:
                issues_found.append(f"  ✗ Sheet 15: '{column}' column MISSING")
                all_bc_columns_found = False
        
        # Check for Compliance_Status formula (complex AND formula)
        if critical_columns_bc["Compliance_Status"]:
            col_letter = critical_columns_bc["Compliance_Status"]
            cell_val = ws[f"{col_letter}5"].value
            if cell_val and isinstance(cell_val, str) and cell_val.startswith("="):
                if "AND(" in cell_val.upper():
                    print(f"  ✓ Sheet 15: Compliance_Status formula with AND logic ({col_letter}5)")
                else:
                    warnings_found.append(f"  ⚠ Sheet 15: Compliance_Status formula lacks AND logic")
            else:
                issues_found.append(f"  ✗ Sheet 15: Compliance_Status formula MISSING ({col_letter}5)")
        
        # Check for conditional formatting (critical role compliance)
        if len(ws.conditional_formatting) > 0:
            print(f"  ✓ Sheet 15: Conditional formatting present ({len(ws.conditional_formatting)} rules)")
        else:
            warnings_found.append(f"  ⚠ Sheet 15: No conditional formatting detected")
        
    else:
        issues_found.append(f"  ✗ Sheet 15 (Business_Continuity_Plan) MISSING - AUDIT CRITICAL")
    
    # ========================================================================
    # CHECK 8: FORMULA INTEGRITY (IFERROR wrappers on VLOOKUP)
    # ========================================================================
    print("\n" + "=" * 80)
    print("CHECK 8: FORMULA INTEGRITY (IFERROR wrappers)")
    print("=" * 80)
    
    formula_issues = 0
    vlookup_count = 0
    vlookup_with_iferror = 0
    
    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        for row in ws.iter_rows():
            for cell in row:
                if cell.value and isinstance(cell.value, str) and cell.value.startswith('='):
                    formula = cell.value
                    
                    # Count VLOOKUPs and check for IFERROR wrappers
                    if "VLOOKUP(" in formula.upper():
                        vlookup_count += 1
                        if "IFERROR(" in formula.upper():
                            vlookup_with_iferror += 1
                    
                    # Check for invalid sheet references
                    if "!" in formula:
                        quoted_refs = re.findall(r"'([^']+)'!", formula)
                        unquoted_refs = re.findall(r"(?<!')([A-Za-z_][A-Za-z0-9_]*)!", formula)
                        sheet_refs = quoted_refs + unquoted_refs
                        for ref in sheet_refs:
                            ref_clean = ref.strip("'")
                            if ref_clean not in wb.sheetnames and "[" not in ref_clean:
                                issues_found.append(
                                    f"  ✗ {sheet_name}!{cell.coordinate}: "
                                    f"Invalid sheet reference '{ref_clean}'"
                                )
                                formula_issues += 1
    
    print(f"  ✓ Total VLOOKUP formulas found: {vlookup_count}")
    if vlookup_count > 0:
        iferror_percentage = (vlookup_with_iferror / vlookup_count) * 100
        print(f"  ✓ VLOOKUPs with IFERROR wrapper: {vlookup_with_iferror} ({iferror_percentage:.1f}%)")
        
        if iferror_percentage < 90:
            warnings_found.append(f"  ⚠ Only {iferror_percentage:.1f}% of VLOOKUPs have IFERROR wrappers (target: 100%)")
        else:
            print(f"  ✓ IFERROR wrapper coverage excellent")
    
    if formula_issues == 0:
        print(f"  ✓ All formulas reference valid sheets")
    else:
        print(f"  ✗ {formula_issues} formula issues detected")
    
    # ========================================================================
    # CHECK 9: ACTION_ITEMS (v2.0 - new issue types)
    # ========================================================================
    print("\n" + "=" * 80)
    print("CHECK 9: ACTION_ITEMS (v2.0 - new issue types)")
    print("=" * 80)
    
    if "Action_Items" in wb.sheetnames:
        ws = wb["Action_Items"]
        
        # Check for new issue types in data validation
        issue_type_validation_found = False
        for dv in ws.data_validations.dataValidation:
            if dv.formula1 and "Integration" in str(dv.formula1):
                issue_type_validation_found = True
                if "CVSS_Accuracy" in str(dv.formula1) and "Continuity" in str(dv.formula1):
                    print(f"  ✓ Action_Items: v2.0 issue types found (Integration, CVSS_Accuracy, Continuity)")
                    break
        
        if not issue_type_validation_found:
            warnings_found.append(f"  ⚠ Action_Items: v2.0 issue types not detected")
        
        # Check for Detected_In_Sheet column
        detected_sheet_found = False
        for col in range(1, 20):
            col_letter = get_column_letter(col)
            header_val = ws[f"{col_letter}4"].value
            if header_val and "DETECTED_IN_SHEET" in str(header_val).upper():
                detected_sheet_found = True
                print(f"  ✓ Action_Items: 'Detected_In_Sheet' column found ({col_letter})")
                break
        
        if not detected_sheet_found:
            warnings_found.append(f"  ⚠ Action_Items: 'Detected_In_Sheet' column not found")
    
    # ========================================================================
    # SUMMARY
    # ========================================================================
    print("\n" + "=" * 80)
    print("VALIDATION SUMMARY")
    print("=" * 80)
    
    if issues_found:
        print(f"\n✗ CRITICAL ISSUES: {len(issues_found)}")
        for issue in issues_found:
            print(issue)
    
    if warnings_found:
        print(f"\n⚠ WARNINGS: {len(warnings_found)}")
        for warning in warnings_found:
            print(warning)
    
    if not issues_found and not warnings_found:
        print("\n🎉 VALIDATION PASSED")
        print("\nWorkbook structure is valid for v2.0:")
        print("  • 15 sheets (expanded from 8)")
        print("  • CVSS v4.0/3.1 support tracking (Sheet 2)")
        print("  • CVSS accuracy assessment (Sheet 3)")
        print("  • Geographic/Sector/Threat coverage matrix (Sheet 4)")
        print("  • Cost analysis with ROI calculations (Sheet 5)")
        print("  • GDPR/FADP/DPA compliance tracking (Sheet 6)")
        print("  • Vendor management (Sheets 9-13)")
        print("  • Quarterly source validation - AUDIT CRITICAL (Sheet 14)")
        print("  • Business continuity planning - AUDIT CRITICAL (Sheet 15)")
        print("\n✓ Ready for ISO 27001:2022 Control A.5.7 audit")
    
    print("\n" + "=" * 80)
    wb.close()


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("=" * 70)
        print("ISMS Control A.5.7.1 v2.0 - Threat Intelligence Sources")
        print("Excel Sanity Checker (15 Sheets)")
        print("=" * 70)
        print("\nUsage: python3 excel_sanity_check_a57_1_v2.py <filename.xlsx>")
        print("\nExample:")
        print("  python3 excel_sanity_check_a57_1_v2.py ISMS_A_5_7_1_Sources_Assessment_20250109.xlsx")
        print("\n'Evidence > Theater' - Systems Engineering ISMS")
        sys.exit(1)
    
    filename = sys.argv[1]
    
    try:
        check_workbook_health(filename)
    except FileNotFoundError:
        print(f"\n✗ ERROR: File not found: {filename}")
        sys.exit(1)
    except Exception as e:
        print(f"\n✗ ERROR: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()