#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
================================================================================
Excel Workbook Sanity Checker - ISMS A.8.28 Assessment Workbooks
================================================================================

ISO/IEC 27001:2022 Control A.8.28: Secure Coding
Quality Assurance Utility: Excel File Integrity Validation

--------------------------------------------------------------------------------
SAMPLE SCRIPT - REQUIRES CUSTOMIZATION FOR YOUR ORGANIZATION
--------------------------------------------------------------------------------

This script is a TEMPLATE/SAMPLE implementation and MUST be adapted to match
your organization's specific assessment workbook structures and Excel file
quality requirements.

Key customization areas:
1. Expected workbook structures (match your actual A.8.28 assessment designs)
2. Formula validation patterns (specific to your calculation requirements)
3. Style consistency rules (based on your formatting standards)
4. Data validation schema checks (adapt to your dropdown/validation needs)
5. Diagnostic severity thresholds (aligned with your quality tolerance)

DO NOT use this script without reviewing and adapting all sections marked
with "# CUSTOMIZE:" comments throughout the code.

Reference Pattern: Based on ISMS-A.8.28 Secure Coding Assessment Framework

--------------------------------------------------------------------------------
DESCRIPTION
--------------------------------------------------------------------------------

Diagnostic utility for troubleshooting Excel's "file level validation and repair"
warnings when opening A.8.28 secure coding assessment workbooks generated by
openpyxl scripts.

**Purpose:**
Identifies common openpyxl-generated Excel issues that trigger repair warnings,
enabling proactive quality assurance and preventing stakeholder confusion when
opening assessment workbooks.

**Problem Statement:**
When Excel opens workbooks generated by openpyxl, it may display warnings:
- "We found a problem with some content in [filename]. Do you want to recover?"
- "Excel completed file level validation and repair. Some parts of this
  workbook may have been repaired or discarded."

These warnings, while often cosmetic, undermine stakeholder confidence and
create audit concerns. This script identifies root causes before distribution.

**Common Issues Detected:**

1. Formula Syntax Errors
   - Invalid cell references (e.g., references to non-existent sheets)
   - Malformed formula syntax
   - Circular reference warnings
   - Array formula inconsistencies

2. Data Validation Conflicts
   - Overlapping validation ranges
   - Invalid validation formulas
   - Conflicting dropdown lists
   - Range reference errors in validation rules

3. Style Attribute Inconsistencies
   - Malformed font definitions
   - Invalid color specifications
   - Corrupted number formats
   - Border style conflicts

4. Merged Cell Content Issues
   - Content in non-primary merged cell positions
   - Inconsistent merge ranges
   - Overlapping merge regions

5. Worksheet Structure Problems
   - Invalid sheet names (illegal characters, length)
   - Duplicate sheet names
   - Hidden sheet inconsistencies
   - Protection attribute conflicts

6. Named Range Issues
   - Invalid name definitions
   - Conflicting scope definitions
   - Circular name references

**When to Use:**

Critical Usage Scenarios:
- Excel displays repair warnings when opening generated workbooks
- After modifying assessment generator scripts
- Before distributing workbooks to stakeholders (especially auditors)
- Quality assurance validation before consolidation
- After openpyxl library version upgrades

Preventive Usage:
- As part of CI/CD testing for script changes
- Regular validation of assessment templates
- Before major assessment campaigns

**Diagnostic Process:**

1. **Load Workbook**: Opens Excel file using openpyxl in read-only mode
2. **Structural Analysis**: Validates sheet structure and naming
3. **Formula Validation**: Parses and validates all formula cells
4. **Data Validation Check**: Examines data validation rules and ranges
5. **Style Consistency**: Checks for malformed style attributes
6. **Merge Analysis**: Validates merged cell configurations
7. **Report Generation**: Categorizes findings by severity and provides
   remediation guidance

**Output Categories:**

- **CRITICAL**: Issues that cause Excel repair dialogs or data loss
  Examples: Broken formulas, invalid sheet references, corrupted cells

- **WARNING**: Issues that may cause Excel warnings but don't break functionality
  Examples: Style inconsistencies, unusual formatting, minor validation conflicts

- **INFO**: Cosmetic or best-practice issues that don't affect Excel behavior
  Examples: Non-standard naming, optimization opportunities

--------------------------------------------------------------------------------
REQUIREMENTS
--------------------------------------------------------------------------------

System Requirements:
    - Python 3.8 or higher
    - openpyxl library for Excel file analysis

Installation:
    Ubuntu/Debian:
        sudo apt install python3-openpyxl
    
    Or via pip:
        pip3 install openpyxl

Dependencies:
    - openpyxl >= 3.0.0 (Python Excel library)
    - re (standard library - regex for formula parsing)
    - datetime (standard library)

--------------------------------------------------------------------------------
USAGE
--------------------------------------------------------------------------------

Basic Usage:
    python3 excel_sanity_check_a828.py ISMS_A_8_28_1_SDLC_Assessment_20250124.xlsx

Advanced Usage:
    # Check specific assessment domain
    python3 excel_sanity_check_a828.py ISMS_A_8_28_2_Standards_Tools_Assessment_20250124.xlsx
    
    # Check all A.8.28 assessment files in directory
    python3 excel_sanity_check_a828.py --all
    
    # Generate detailed diagnostic report
    python3 excel_sanity_check_a828.py --verbose ISMS_A_8_28_3_Code_Review_Testing_Assessment_20250124.xlsx
    
    # Output report to file
    python3 excel_sanity_check_a828.py --output report.txt ISMS_A_8_28_4_Third_Party_OSS_Assessment_20250124.xlsx
    
    # Check only critical issues
    python3 excel_sanity_check_a828.py --severity critical ISMS_A_8_28_5_Compliance_Dashboard_20250124.xlsx
    
    # JSON output for automated processing
    python3 excel_sanity_check_a828.py --format json ISMS_A_8_28_1_SDLC_Assessment_20250124.xlsx

Command-Line Options:
    filename                Excel file to check (required unless --all used)
    --all                   Check all A.8.28 assessment files in current directory
    --verbose               Display detailed diagnostic information
    --output FILE           Write report to specified file (default: stdout)
    --severity LEVEL        Filter by severity: critical|warning|info|all (default: all)
    --format FORMAT         Output format: text|json|html (default: text)
    --fix-suggestions       Include automated fix suggestions in report
    --compare-original      Compare with backup file to identify introduced issues

Typical Workflow:

    1. Generate assessment workbook with assessment script:
       python3 generate_a828_1_sdlc_assessment.py
    
    2. Run sanity check before distribution:
       python3 excel_sanity_check_a828.py ISMS_A_8_28_1_SDLC_Assessment_20250124.xlsx
    
    3. If issues found, review diagnostic report
    
    4. Fix issues in generator script (not in Excel file manually)
    
    5. Regenerate workbook and re-validate
    
    6. Distribute only after clean sanity check

Output Example:

    ================================================================================
    Excel Workbook Sanity Check - ISMS A.8.28 Assessment
    ================================================================================
    
    File: ISMS_A_8_28_1_SDLC_Assessment_20250124.xlsx
    Checked: 2025-01-24 14:32:15
    
    SUMMARY:
    --------
    Total Issues Found: 3
    - CRITICAL: 1
    - WARNING: 2
    - INFO: 0
    
    CRITICAL ISSUES:
    ----------------
    [CRITICAL-001] Formula Error in Sheet "SDLC Gates"
        Cell: E15
        Issue: Invalid sheet reference in formula: =SUM('NonExistent Sheet'!A1:A10)
        Impact: Excel will display repair dialog on open
        Remediation: Correct sheet name in formula or create referenced sheet
    
    WARNING ISSUES:
    ---------------
    [WARNING-001] Data Validation Overlap in Sheet "Requirements Phase"
        Cells: B5:B20 and B15:B30
        Issue: Overlapping validation ranges may cause inconsistent behavior
        Impact: Minor - Excel may show unexpected validation lists
        Remediation: Consolidate validation ranges or ensure no overlap
    
    [WARNING-002] Style Attribute Inconsistency in Sheet "Evidence Register"
        Cell: G25
        Issue: Font definition contains unsupported attribute
        Impact: Minor - Excel may reset font to default on repair
        Remediation: Use standard font attributes only
    
    RECOMMENDATIONS:
    ----------------
    1. Fix CRITICAL issues before distribution to stakeholders
    2. Review generator script formula generation logic (line ~450)
    3. Consider consolidating data validation rules to prevent overlap
    
    ================================================================================

--------------------------------------------------------------------------------
METADATA
--------------------------------------------------------------------------------

Control Reference:    ISO/IEC 27001:2022 Annex A Control A.8.28
Utility Type:         Quality Assurance - Excel File Integrity Validation
Framework Version:    1.0
Script Version:       1.0
Author:               [Organization ISMS Team]
Date:                 DD.MM.YYYY
Last Modified:        DD.MM.YYYY
Python Version:       3.8+
License:              [Organization License/Terms]

Related Documents:
    - ISMS-POL-A.8.28: Secure Coding Policy (Governance)
    - ISMS-IMP-A.8.28.1: SDLC Integration Assessment (Domain 1)
    - ISMS-IMP-A.8.28.2: Standards & Tools Assessment (Domain 2)
    - ISMS-IMP-A.8.28.3: Code Review & Testing Assessment (Domain 3)
    - ISMS-IMP-A.8.28.4: Third-Party & OSS Assessment (Domain 4)
    - ISMS-IMP-A.8.28.5: Compliance Dashboard (Consolidation)

Related Scripts:
    - generate_a828_1_sdlc_assessment.py (generates workbook 1)
    - generate_a828_2_standards_tools.py (generates workbook 2)
    - generate_a828_3_code_review_testing.py (generates workbook 3)
    - generate_a828_4_third_party_oss.py (generates workbook 4)
    - generate_a828_5_compliance_dashboard.py (generates dashboard)
    - normalize_assessment_files_a828.py (data normalization utility)
    - excel_style_object_checker_a828.py (deep style analysis)
    - excel_style_object_patcher_a828.py (automated style fixes)

--------------------------------------------------------------------------------
CHANGE HISTORY
--------------------------------------------------------------------------------

Version 1.0 - DD.MM.YYYY
    - Initial release
    - Implements comprehensive Excel file integrity validation
    - Detects common openpyxl-generated issues
    - Provides structured diagnostic reporting
    - Supports all A.8.28 assessment domains

[Future changes to be documented here]

--------------------------------------------------------------------------------
IMPORTANT NOTES
--------------------------------------------------------------------------------

**Philosophy - Prevent Rather Than Repair:**
This script helps identify issues BEFORE stakeholders encounter them. It's
cheaper to fix the generator script once than to explain Excel repair warnings
to 50 confused auditors or executives.

**Excel Repair Warnings Are Not Benign:**
While many repair warnings are cosmetic, they create several real problems:
- Stakeholders question data integrity ("Is my data corrupted?")
- Auditors raise concerns about tool reliability
- Recipients may not approve repaired files
- Some repairs DO cause data/formatting loss

Even cosmetic warnings are worth fixing for professional quality.

**openpyxl vs Excel Internal Format:**
openpyxl generates Office Open XML (OOXML) format, which Excel then validates.
Excel's validation is stricter than openpyxl's generation. This script bridges
that gap by checking for Excel-specific validation rules.

**Don't Edit Generated Files Manually:**
If this script finds issues, fix them in the GENERATOR SCRIPT, not in Excel.
Manual Excel edits will be lost when you regenerate the workbook. The generator
script is the source of truth.

**Common Root Causes:**

1. **Dynamic Sheet References**: Building formulas with sheet names that don't
   exist yet or have been renamed. Solution: Validate sheet existence before
   referencing in formulas.

2. **Copy-Paste Style Objects**: Reusing style objects across cells can cause
   attribute conflicts. Solution: Create new style objects or use cell.style
   references carefully.

3. **Data Validation Formula Scope**: Validation formulas referencing cells
   outside validation range. Solution: Use proper absolute/relative references.

4. **Merged Cell Content**: Writing to all cells in merge range instead of just
   the top-left cell. Solution: Only write to merged_cell.min_row, min_col.

**Automated vs Manual Fixes:**

Some issues can be auto-fixed by companion scripts:
- excel_style_object_patcher_a828.py: Fixes style inconsistencies
- normalize_assessment_files_a828.py: Fixes data format issues

This sanity checker ONLY reports issues - it doesn't modify files. This is
intentional: diagnostic and repair are separate concerns.

**Performance Considerations:**
Checking large workbooks (10+ sheets, 10,000+ cells) may take 10-30 seconds.
This is acceptable for quality assurance but not suitable for real-time
validation in automated workflows.

**False Positives:**
Script may flag intentional design choices as "issues":
- Complex formulas may be flagged as "unusual" but are correct
- Custom number formats may be flagged but are valid
- Review WARNING and INFO items with judgment

**Integration with CI/CD:**
This script can be integrated into automated testing:
```bash
# Exit with error code if CRITICAL issues found
python3 excel_sanity_check_a828.py --severity critical --format json \
    ISMS_A_8_28_1_SDLC_Assessment_20250124.xlsx || exit 1
```

**When Issues Persist:**
If you've fixed issues in the generator script but sanity check still fails:
1. Ensure you're checking the NEWLY generated file, not old version
2. Check openpyxl version (some issues are version-specific)
3. Try opening/saving in Excel, then check with openpyxl (Excel may normalize)
4. Review openpyxl documentation for known issues with your Excel version

**Reporting to openpyxl Project:**
If you identify genuine openpyxl bugs (generates invalid OOXML), report to:
https://openpyxl.readthedocs.io/en/stable/

Include minimal reproducible example and this script's diagnostic output.

**Excel Version Compatibility:**
This script validates against Office Open XML standards, which are consistent
across Excel versions (2010+). However, some features (e.g., advanced charts,
Power Query) may behave differently across versions.

Test generated workbooks with Excel versions your stakeholders actually use.

**Quality Assurance Philosophy:**
Run this check on EVERY generated workbook before distribution, not just when
you suspect issues. Prevention is better than explanation.

**Don't Fool Yourself - Feynman Principle:**
"It works on my machine" is not acceptable for audit evidence. If Excel shows
repair warnings, it's broken - even if the data looks fine after repair.

Your stakeholders deserve workbooks that open cleanly without warnings.

================================================================================
"""

import openpyxl
import sys
from pathlib import Path
from datetime import datetime

# ============================================================================
# VALIDATION RULES
# ============================================================================

WORKBOOK_SPECS = {
    "A.8.28.1": {
        "pattern": "8.28.1",
        "required_sheets": ["Instructions", "Summary_Dashboard", "Evidence_Register", 
                           "Gap_Analysis", "Approval_Sign_Off"],
        "min_domain_sheets": 5,  # Should have 5-6 domain sheets
    },
    "A.8.28.2": {
        "pattern": "8.28.2",
        "required_sheets": ["Instructions", "Summary_Dashboard", "Evidence_Register",
                           "Gap_Analysis", "Approval_Sign_Off"],
        "min_domain_sheets": 5,
    },
    "A.8.28.3": {
        "pattern": "8.28.3",
        "required_sheets": ["Instructions", "Summary_Dashboard", "Evidence_Register",
                           "Gap_Analysis", "Approval_Sign_Off"],
        "min_domain_sheets": 5,
    },
    "A.8.28.4": {
        "pattern": "8.28.4",
        "required_sheets": ["Instructions", "Summary_Dashboard", "Evidence_Register",
                           "Gap_Analysis", "Approval_Sign_Off"],
        "min_domain_sheets": 5,
    },
    "A.8.28.5": {
        "pattern": "8.28.5",
        "required_sheets": ["Instructions", "Executive_Summary", "Approval_Sign_Off"],
        "min_domain_sheets": 0,  # Dashboard has different structure
    },
}


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def identify_workbook_type(filename):
    """Identify workbook type from filename."""
    filename_str = str(filename).upper()
    for wb_type, spec in WORKBOOK_SPECS.items():
        if spec["pattern"].upper() in filename_str:
            return wb_type
    return None


def print_header(text):
    """Print formatted section header."""
    print("\n" + "=" * 70)
    print(f"  {text}")
    print("=" * 70)


def print_check(passed, message):
    """Print check result with status icon."""
    icon = "✅" if passed else "❌"
    print(f"  {icon} {message}")
    return passed


# ============================================================================
# VALIDATION CHECKS
# ============================================================================

def check_file_opens(filepath):
    """Check if file opens without errors."""
    print_header("CHECK 1: File Integrity")
    try:
        wb = openpyxl.load_workbook(filepath, data_only=False)
        wb.close()
        return print_check(True, f"File opens successfully: {filepath.name}")
    except Exception as e:
        return print_check(False, f"File cannot be opened: {e}")


def check_required_sheets(filepath, wb_type):
    """Verify required sheets exist."""
    print_header("CHECK 2: Required Sheets")
    
    if not wb_type:
        print_check(False, "Unknown workbook type, skipping sheet check")
        return True
    
    spec = WORKBOOK_SPECS[wb_type]
    required = spec["required_sheets"]
    
    try:
        wb = openpyxl.load_workbook(filepath, data_only=False)
        actual_sheets = wb.sheetnames
        wb.close()
        
        missing = [s for s in required if s not in actual_sheets]
        
        if missing:
            print_check(False, f"Missing required sheets: {', '.join(missing)}")
            return False
        else:
            print_check(True, f"All {len(required)} required sheets present")
            
            # Check domain sheet count
            if spec["min_domain_sheets"] > 0:
                domain_count = len([s for s in actual_sheets if s not in required])
                if domain_count >= spec["min_domain_sheets"]:
                    print_check(True, f"Has {domain_count} domain assessment sheets")
                else:
                    print_check(False, f"Expected ≥{spec['min_domain_sheets']} domain sheets, found {domain_count}")
                    return False
            
            return True
            
    except Exception as e:
        return print_check(False, f"Error reading sheets: {e}")


def check_formulas(filepath):
    """Check for broken formulas (#REF!, #VALUE!, #NAME?)."""
    print_header("CHECK 3: Formula Validation")
    
    try:
        wb = openpyxl.load_workbook(filepath, data_only=False)
        
        error_patterns = ["#REF!", "#VALUE!", "#NAME?", "#DIV/0!", "#NULL!"]
        errors_found = []
        
        for sheet_name in wb.sheetnames:
            ws = wb[sheet_name]
            for row in ws.iter_rows():
                for cell in row:
                    if cell.value and isinstance(cell.value, str):
                        for error in error_patterns:
                            if error in cell.value:
                                errors_found.append(f"{sheet_name}!{cell.coordinate}: {error}")
        
        wb.close()
        
        if errors_found:
            print_check(False, f"Found {len(errors_found)} formula errors:")
            for error in errors_found[:10]:  # Show first 10
                print(f"      {error}")
            if len(errors_found) > 10:
                print(f"      ... and {len(errors_found) - 10} more")
            return False
        else:
            return print_check(True, "No formula errors detected")
            
    except Exception as e:
        return print_check(False, f"Error checking formulas: {e}")


def check_dropdowns(filepath):
    """Check if dropdowns are configured."""
    print_header("CHECK 4: Dropdown Validation")
    
    try:
        wb = openpyxl.load_workbook(filepath, data_only=False)
        
        dropdown_count = 0
        sheets_with_dropdowns = []
        
        for sheet_name in wb.sheetnames:
            ws = wb[sheet_name]
            if hasattr(ws, 'data_validations') and ws.data_validations.dataValidation:
                sheet_dropdown_count = len(ws.data_validations.dataValidation)
                if sheet_dropdown_count > 0:
                    dropdown_count += sheet_dropdown_count
                    sheets_with_dropdowns.append(sheet_name)
        
        wb.close()
        
        if dropdown_count > 0:
            print_check(True, f"Found {dropdown_count} dropdowns across {len(sheets_with_dropdowns)} sheets")
            return True
        else:
            print_check(False, "No dropdowns found (expected for input sheets)")
            return False
            
    except Exception as e:
        return print_check(False, f"Error checking dropdowns: {e}")


def check_sheet_structure(filepath, wb_type):
    """Check basic sheet structure (headers, freeze panes)."""
    print_header("CHECK 5: Sheet Structure")
    
    try:
        wb = openpyxl.load_workbook(filepath, data_only=False)
        
        checks_passed = 0
        checks_total = 0
        
        # Check for frozen panes in assessment sheets
        for sheet_name in wb.sheetnames:
            if sheet_name not in ["Instructions", "Approval_Sign_Off"]:
                ws = wb[sheet_name]
                checks_total += 1
                if ws.freeze_panes:
                    checks_passed += 1
        
        wb.close()
        
        if checks_total > 0:
            pass_rate = (checks_passed / checks_total) * 100
            if pass_rate >= 80:
                return print_check(True, f"Freeze panes set on {checks_passed}/{checks_total} sheets ({pass_rate:.0f}%)")
            else:
                return print_check(False, f"Only {checks_passed}/{checks_total} sheets have freeze panes")
        else:
            return print_check(True, "Structure check complete (no assessment sheets)")
            
    except Exception as e:
        return print_check(False, f"Error checking structure: {e}")


def check_workbook_metadata(filepath):
    """Check workbook properties and metadata."""
    print_header("CHECK 6: Workbook Metadata")
    
    try:
        wb = openpyxl.load_workbook(filepath, data_only=False)
        
        checks = []
        
        # Check title
        if wb.properties.title:
            checks.append(print_check(True, f"Title: {wb.properties.title}"))
        else:
            checks.append(print_check(False, "No workbook title set"))
        
        # Check sheet count
        sheet_count = len(wb.sheetnames)
        checks.append(print_check(True, f"Total sheets: {sheet_count}"))
        
        # Check creator
        if wb.properties.creator:
            checks.append(print_check(True, f"Creator: {wb.properties.creator}"))
        
        wb.close()
        
        return all(checks)
        
    except Exception as e:
        return print_check(False, f"Error checking metadata: {e}")


# ============================================================================
# MAIN VALIDATION FUNCTION
# ============================================================================

def validate_workbook(filepath):
    """Run all validation checks on a workbook."""
    filepath = Path(filepath)
    
    if not filepath.exists():
        print(f"❌ Error: File not found: {filepath}")
        return False
    
    print("\n" + "=" * 70)
    print(f"  ISMS CONTROL 8.28 - WORKBOOK SANITY CHECK")
    print(f"  File: {filepath.name}")
    print(f"  Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 70)
    
    # Identify workbook type
    wb_type = identify_workbook_type(filepath.name)
    if wb_type:
        print(f"\n📋 Detected workbook type: {wb_type}")
    else:
        print(f"\n⚠️  Could not detect workbook type from filename")
    
    # Run all checks
    checks = [
        check_file_opens(filepath),
        check_required_sheets(filepath, wb_type),
        check_formulas(filepath),
        check_dropdowns(filepath),
        check_sheet_structure(filepath, wb_type),
        check_workbook_metadata(filepath),
    ]
    
    passed = sum(checks)
    total = len(checks)
    
    # Summary
    print("\n" + "=" * 70)
    print(f"  VALIDATION SUMMARY")
    print("=" * 70)
    print(f"  Checks passed: {passed}/{total}")
    print(f"  Success rate:  {(passed/total)*100:.0f}%")
    
    if passed == total:
        print(f"\n  ✅ ALL CHECKS PASSED - Workbook is valid!")
    elif passed >= total * 0.8:
        print(f"\n  ⚠️  MOSTLY VALID - {total - passed} minor issues found")
    else:
        print(f"\n  ❌ VALIDATION FAILED - {total - passed} critical issues found")
    
    print("=" * 70 + "\n")
    
    return passed == total


def validate_all_workbooks(directory="."):
    """Validate all A.8.28 workbooks in directory."""
    directory = Path(directory)
    
    print("\n" + "=" * 70)
    print("  BATCH VALIDATION MODE")
    print("  Scanning for Control 8.28 workbooks...")
    print("=" * 70)
    
    # Find all relevant workbooks
    patterns = ["*8.28.1*.xlsx", "*8.28.2*.xlsx", "*8.28.3*.xlsx", 
                "*8.28.4*.xlsx", "*8.28.5*.xlsx"]
    
    workbooks = []
    for pattern in patterns:
        workbooks.extend(directory.glob(pattern))
    
    # Filter out temporary files
    workbooks = [wb for wb in workbooks if not wb.name.startswith("~$")]
    
    if not workbooks:
        print(f"\n❌ No Control 8.28 workbooks found in {directory}\n")
        return False
    
    print(f"\nFound {len(workbooks)} workbook(s):\n")
    for wb in workbooks:
        print(f"  • {wb.name}")
    
    print()
    
    # Validate each workbook
    results = {}
    for wb in workbooks:
        results[wb.name] = validate_workbook(wb)
    
    # Final summary
    print("\n" + "=" * 70)
    print("  BATCH VALIDATION SUMMARY")
    print("=" * 70)
    
    for filename, passed in results.items():
        icon = "✅" if passed else "❌"
        print(f"  {icon} {filename}")
    
    passed_count = sum(results.values())
    total_count = len(results)
    
    print()
    print(f"  Total: {passed_count}/{total_count} workbooks passed validation")
    print("=" * 70 + "\n")
    
    return passed_count == total_count


# ============================================================================
# COMMAND LINE INTERFACE
# ============================================================================

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Validate ISMS Control 8.28 assessment workbooks",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Validate single workbook
  python3 excel_sanity_check_a828.py ISMS-IMP-A.8.28.1_SDLC_Assessment_20250107.xlsx
  
  # Validate all workbooks in current directory
  python3 excel_sanity_check_a828.py --all
  
  # Validate all workbooks in specific directory
  python3 excel_sanity_check_a828.py --all --directory ./assessments
        """
    )
    
    parser.add_argument(
        'workbook',
        nargs='?',
        help='Path to Excel workbook to validate'
    )
    
    parser.add_argument(
        '--all', '-a',
        action='store_true',
        help='Validate all Control 8.28 workbooks in directory'
    )
    
    parser.add_argument(
        '--directory', '-d',
        default='.',
        help='Directory to scan for workbooks (default: current directory)'
    )
    
    args = parser.parse_args()
    
    # Validate mode
    if args.all:
        success = validate_all_workbooks(args.directory)
    elif args.workbook:
        success = validate_workbook(args.workbook)
    else:
        parser.print_help()
        print("\n❌ Error: Must specify workbook or use --all flag\n")
        sys.exit(1)
    
    sys.exit(0 if success else 1)