import { Routes } from '@angular/router'
import { authGuard } from './core/guards/auth.guard'

export const routes: Routes = [
  {
    path: 'login',
    loadComponent: () => import('./pages/login/login.component').then(m => m.LoginComponent),
  },
  {
    path: '',
    loadComponent: () => import('./layout/layout.component').then(m => m.LayoutComponent),
    canActivate: [authGuard],
    children: [
      { path: '', loadComponent: () => import('./pages/home/home.component').then(m => m.HomeComponent) },
      { path: 'overview', loadComponent: () => import('./pages/overview/overview.component').then(m => m.OverviewComponent) },
      { path: 'coverage', loadComponent: () => import('./pages/coverage/coverage.component').then(m => m.CoverageComponent) },
      { path: 'gaps', loadComponent: () => import('./pages/gaps/gaps.component').then(m => m.GapsComponent) },
      { path: 'controls', loadComponent: () => import('./pages/controls/controls.component').then(m => m.ControlsComponent) },
      { path: 'controls/code/:code', loadComponent: () => import('./pages/control-detail/control-detail.component').then(m => m.ControlDetailComponent) },
      { path: 'controls/:id', loadComponent: () => import('./pages/control-detail/control-detail.component').then(m => m.ControlDetailComponent) },
      { path: 'framework-controls/:code/:controlId', loadComponent: () => import('./pages/framework-control-detail/framework-control-detail.component').then(m => m.FrameworkControlDetailComponent) },
      { path: 'assessments', loadComponent: () => import('./pages/assessments/assessments.component').then(m => m.AssessmentsComponent) },
      { path: 'collections/:id', loadComponent: () => import('./pages/collection-detail/collection-detail.component').then(m => m.CollectionDetailComponent) },
      { path: 'policies', loadComponent: () => import('./pages/policies/policies.component').then(m => m.PoliciesComponent) },
      { path: 'search', loadComponent: () => import('./pages/search/search.component').then(m => m.SearchComponent) },
      { path: 'evidence', loadComponent: () => import('./pages/evidence/evidence.component').then(m => m.EvidenceComponent) },
      { path: 'graph', loadComponent: () => import('./pages/graph/graph.component').then(m => m.GraphComponent) },
      { path: 'admin', loadComponent: () => import('./pages/admin/admin.component').then(m => m.AdminComponent) },
      { path: 'admin/logs', loadComponent: () => import('./pages/logs/logs.component').then(m => m.LogsComponent) },
      { path: 'system', loadComponent: () => import('./pages/system/system.component').then(m => m.SystemComponent) },
      { path: 'connectors', loadComponent: () => import('./pages/connectors/connectors.component').then(m => m.ConnectorsComponent) },
      { path: 'qa', loadComponent: () => import('./pages/qa/qa.component').then(m => m.QaComponent) },
      { path: 'generators', loadComponent: () => import('./pages/generators/generators.component').then(m => m.GeneratorsComponent) },
      { path: 'compass', loadComponent: () => import('./pages/compass/compass.component').then(m => m.CompassComponent) },
      { path: 'report', loadComponent: () => import('./pages/report/report.component').then(m => m.ReportComponent) },
      { path: 'risk', loadComponent: () => import('./pages/risk/risk.component').then(m => m.RiskComponent) },
      { path: 'projects', loadComponent: () => import('./pages/projects/projects.component').then(m => m.ProjectsComponent) },
      { path: 'projects/:id', loadComponent: () => import('./pages/project-detail/project-detail.component').then(m => m.ProjectDetailComponent) },
      { path: 'organisations', loadComponent: () => import('./pages/organisations/organisations.component').then(m => m.OrganisationsComponent) },
      { path: 'risk-register', loadComponent: () => import('./pages/risk-register/risk-register.component').then(m => m.RiskRegisterComponent) },
      { path: 'remediation', loadComponent: () => import('./pages/remediation/remediation.component').then(m => m.RemediationComponent) },
      { path: 'metrics', loadComponent: () => import('./pages/metrics/metrics.component').then(m => m.MetricsComponent) },
      { path: 'bia', loadComponent: () => import('./pages/bia/bia.component').then(m => m.BiaComponent) },
      { path: 'ebios', loadComponent: () => import('./pages/ebios/ebios.component').then(m => m.EbiosComponent) },
      { path: 'tprm', loadComponent: () => import('./pages/tprm/tprm.component').then(m => m.TprmComponent) },
      { path: 'csrm', loadComponent: () => import('./pages/csrm/csrm.component').then(m => m.CsrmComponent) },
      { path: 'custom-frameworks', loadComponent: () => import('./pages/custom-frameworks/custom-frameworks.component').then(m => m.CustomFrameworksComponent) },
      { path: 'framework-tracker', loadComponent: () => import('./pages/framework-tracker/framework-tracker.component').then(m => m.FrameworkTrackerComponent) },
      { path: 'crosswalk-tracker', loadComponent: () => import('./pages/crosswalk-tracker/crosswalk-tracker.component').then(m => m.CrosswalkTrackerComponent) },
      { path: 'help', loadComponent: () => import('./pages/help/help.component').then(m => m.HelpComponent) },
      { path: 'glossary', loadComponent: () => import('./pages/glossary/glossary.component').then(m => m.GlossaryComponent) },
      { path: 'notifications', loadComponent: () => import('./pages/notifications/notifications.component').then(m => m.NotificationsComponent) },
      { path: 'nist-csf', loadComponent: () => import('./pages/nist-csf/nist-csf.component').then(m => m.NistCsfComponent) },
      { path: 'nist-csf/:id/report', loadComponent: () => import('./pages/nist-csf-report/nist-csf-report.component').then(m => m.NistCsfReportComponent) },
      // ComplianceAssessment — replaces 22 framework stub pages
      { path: 'compliance/:frameworkCode', loadComponent: () => import('./pages/compliance-assessment/compliance-assessment.component').then(m => m.ComplianceAssessmentComponent) },
      // Threat Intelligence
      { path: 'threat-feeds', loadComponent: () => import('./pages/threat-feeds/threat-feeds.component').then(m => m.ThreatFeedsComponent) },
      { path: 'threat-intel', loadComponent: () => import('./pages/threat-intel-dashboard/threat-intel-dashboard.component').then(m => m.ThreatIntelDashboardComponent) },
      { path: 'threat-exposure', loadComponent: () => import('./pages/threat-exposure/threat-exposure.component').then(m => m.ThreatExposureComponent) },
      { path: 'mitre-attack', loadComponent: () => import('./pages/mitre-attack/mitre-attack.component').then(m => m.MitreAttackComponent) },
      { path: 'mitre-atlas', loadComponent: () => import('./pages/mitre-atlas/mitre-atlas.component').then(m => m.MitreAtlasComponent) },
      { path: 'mitre-groups', loadComponent: () => import('./pages/mitre-groups/mitre-groups.component').then(m => m.MitreGroupsComponent) },
      { path: 'mitre-software', loadComponent: () => import('./pages/mitre-software/mitre-software.component').then(m => m.MitreSoftwareComponent) },
      { path: 'mitre-campaigns', loadComponent: () => import('./pages/mitre-campaigns/mitre-campaigns.component').then(m => m.MitreCampaignsComponent) },
      { path: 'mitre-heatmap', loadComponent: () => import('./pages/mitre-heatmap/mitre-heatmap.component').then(m => m.MitreHeatmapComponent) },
      { path: 'cve-explorer', loadComponent: () => import('./pages/cve-explorer/cve-explorer.component').then(m => m.CveExplorerComponent) },
      { path: 'cpe-explorer', loadComponent: () => import('./pages/cpe-explorer/cpe-explorer.component').then(m => m.CpeExplorerComponent) },
      { path: 'euvd-explorer', loadComponent: () => import('./pages/euvd-explorer/euvd-explorer.component').then(m => m.EuvdExplorerComponent) },
      { path: 'ioc-explorer', loadComponent: () => import('./pages/ioc-explorer/ioc-explorer.component').then(m => m.IocExplorerComponent) },
      { path: 'malware-atlas', loadComponent: () => import('./pages/malware-atlas/malware-atlas.component').then(m => m.MalwareAtlasComponent) },
      { path: 'ip-enrichment', loadComponent: () => import('./pages/ip-enrichment/ip-enrichment.component').then(m => m.IpEnrichmentComponent) },
      { path: '**', redirectTo: '' },
    ],
  },
]
