"""Remove stale OWASP_ASVS_4.0 framework after upgrade to 5.0.0.

OWASP ASVS was upgraded from 4.0.3 → 5.0.0 with a new framework code
(OWASP_ASVS_4.0 → OWASP_ASVS_5.0).  Both share name="OWASP ASVS", which
causes the coverage matrix's by_framework dict to be overwritten and show 0.
This migration deletes the orphaned 4.0 framework and its controls.

Revision ID: 064
Revises: 063
Create Date: 2026-05-03
"""

import sqlalchemy as sa
from alembic import op

revision = '064'
down_revision = '063'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()

    # Resolve the framework UUID for OWASP_ASVS_4.0
    row = conn.execute(
        sa.text("SELECT id FROM frameworks WHERE code = 'OWASP_ASVS_4.0' LIMIT 1")
    ).fetchone()

    if row is None:
        return  # already gone

    fw_id = row[0]

    # Delete framework_controls first (FK constraint)
    conn.execute(
        sa.text("DELETE FROM framework_controls WHERE framework_id = :fid"),
        {"fid": fw_id},
    )

    # Delete the framework record
    conn.execute(
        sa.text("DELETE FROM frameworks WHERE id = :fid"),
        {"fid": fw_id},
    )


def downgrade() -> None:
    # The deleted data is regenerated by loading owasp.json with the old generator.
    pass
